### ISSUE TITLE
main.CRITICAL: Notice: Undefined index: SKU

### ISSUE THREAD

**Issue by hederi** [AmpersandHQ/magento2-disable-stock-reservation#34] opened 2020-08-17 14:32 UTC
Magento version 2.3.5-p1

1 - on the checkout screen the error appears "an error on the server prevented your order from being placed please try again
", the order is saved in magento several times, with each customer click.

2 - if I change the name of the sku. "awr" to "awr-A" the order is recorded correctly.

3 - the error does not happen with all products

4 - when I activate the module the error disappears.

----  system.log ------

[2020-08-17 14:13:47] main.CRITICAL: Notice: Undefined index: awr  in /home/allmakes/html/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php on line 127 {"exception":"[object] (Exception(code: 0): Notice: Undefined index: awr  in /home/allmakes/html/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php on line 127 at /home/allmakes/html/vendor/magento/framework/App/ErrorHandler.php:61)"} []

**Comment by convenient** [comment] 2020-08-17 15:20
Hello @hederi 

Thanks for your debugging. 

I think this bug https://github.com/magento/magento2/issues/13128 is meaning we don't have the full backtrace which is annoying and makes it difficult to debug this. Is this replicable for you locally? Could you perhaps edit this part of magento to log a full stack trace so we can know which part of this module is affecting it?

**Comment by hederi** [comment] 2020-08-20 02:52
Hi @convenient 

yes, i replicate locallly.


if you can guide me how to do it.

**Comment by hederi** [comment] 2020-08-20 02:56
look this https://github.com/magento/inventory/issues/2554

**Comment by convenient** [comment] 2020-08-20 10:12
@hederi so you have the error on line 127

```
Undefined index: awr in /home/allmakes/html/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php on line 127
```

Locally if you go into that file you can put some logging in on line 126, or just above to log the stack trace. This should put it in your `support_report.log` or your `system.log` maybe, it will show the full stack trace just before it errors.

```
$exception = new \Exception();
\Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->info($exception->getTraceAsString());
```

This is fine for local development / debugging, never something you would do anywhere near production :)

**Comment by matthewhaworth** [comment] 2020-08-27 08:22
Just a heads up @convenient, I'm getting this too. Not looked into what the cause is yet, but found the issue on github (https://github.com/magento/inventory/issues/2554) and noticed that it linked here!

**Comment by convenient** [comment] 2020-08-27 08:23
@matthewhaworth There are only a few places in this code base that use sku, if I could identify which one is feeding into this function then I should be able to help more :) A trace would be amazingly helpful.

**Comment by pixel75** [comment] 2020-10-06 19:57
same issue to me:
- M2.3.5-p2
- M2ePro
- Paypal, Stripe

Random issue:
when a user pay in system.log:
`[2020-10-06 08:17:12] main.CRITICAL: Exception message: The order wasn't placed. First, agree to the terms and conditions, then try placing your order again.


Trace: <pre>#1 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#2 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#3 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#4 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#5 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Magento/Paypal/Controller/Express/PlaceOrder/Interceptor.php:104]
#6 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#) called at [vendor/magento/framework/App/FrontController.php:162]
#7 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#, &Magento\Paypal\Controller\Express\PlaceOrder\Interceptor#0000000043a40ef700000000737f6c54#) called at [vendor/magento/framework/App/FrontController.php:98]
#8 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#9 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#10 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#11 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000043a40cf800000000737f6c54#, &Closure#0000000043a40c6400000000737f6c54#, &Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#12 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#13 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000043a40cf800000000737f6c54#, &Closure#0000000043a40c6400000000737f6c54#, &Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#14 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#15 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#16 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000043a40d2600000000737f6c54#) called at [vendor/magento/framework/App/Http.php:116]
#17 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#18 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#19 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000043a40d3500000000737f6c54#) called at [index.php:39]
</pre> [] []
**[2020-10-06 08:17:23] main.CRITICAL: Exception message: Notice: Undefined index: casio bag sa  in /var/www/sites/public_html/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php on line 127**
Trace: <pre>#1 Magento\InventorySourceSelectionApi\Model\Algorithms\Result\GetDefaultSortedSourcesResult->execute(&Magento\InventorySourceSelection\Model\Request\InventoryRequest#00000000043da5190000000077ff32a3#, array(&Magento\Inventory\Model\Source#00000000043da1660000000077ff32a3#)) called at [vendor/magento/module-inventory-source-selection/Model/Algorithms/PriorityBasedAlgorithm.php:73]
#2 Magento\InventorySourceSelection\Model\Algorithms\PriorityBasedAlgorithm->execute(&Magento\InventorySourceSelection\Model\Request\InventoryRequest#00000000043da5190000000077ff32a3#) called at [vendor/magento/module-inventory-source-selection-api/Model/SourceSelectionService.php:61]
#3 Magento\InventorySourceSelectionApi\Model\SourceSelectionService->execute(&Magento\InventorySourceSelection\Model\Request\InventoryRequest#00000000043da5190000000077ff32a3#, 'priority') called at [vendor/ampersand/magento2-disable-stock-reservation/src/Model/GetSourceSelectionResultFromOrder.php:89]
#4 Ampersand\DisableStockReservation\Model\GetSourceSelectionResultFromOrder->execute(&Magento\Sales\Model\Order\Interceptor#00000000043da3890000000077ff32a3#) called at [vendor/ampersand/magento2-disable-stock-reservation/src/Plugin/SourceDeductionProcessor.php:95]
#5 Ampersand\DisableStockReservation\Plugin\SourceDeductionProcessor->afterPlace(&Magento\Sales\Model\Service\OrderService\Interceptor#00000000043daf7a0000000077ff32a3#, &Magento\Sales\Model\Order\Interceptor#00000000043da3890000000077ff32a3#, &Magento\Sales\Model\Order\Interceptor#00000000043da3890000000077ff32a3#) called at [vendor/magento/framework/Interception/Interceptor.php:146]
#6 Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Sales\Model\Order\Interceptor#00000000043da3890000000077ff32a3#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#7 Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins('place', array(&Magento\Sales\Model\Order\Interceptor#00000000043da3890000000077ff32a3#), array(array('coupon_uses_incr...'))) called at [generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php:117]
#8 Magento\Sales\Model\Service\OrderService\Interceptor->place(&Magento\Sales\Model\Order\Interceptor#00000000043da3890000000077ff32a3#) called at [vendor/magento/module-quote/Model/QuoteManagement.php:563]
#9 Magento\Quote\Model\QuoteManagement->submitQuote(&Magento\Quote\Model\Quote\Interceptor#00000000043da0ec0000000077ff32a3#, array()) called at [vendor/magento/module-quote/Model/QuoteManagement.php:453]
#10 Magento\Quote\Model\QuoteManagement->submit(&Magento\Quote\Model\Quote\Interceptor#00000000043da0ec0000000077ff32a3#, array()) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('submit', array(&Magento\Quote\Model\Quote\Interceptor#00000000043da0ec0000000077ff32a3#, array())) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Quote\Model\Quote\Interceptor#00000000043da0ec0000000077ff32a3#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('submit', array(&Magento\Quote\Model\Quote\Interceptor#00000000043da0ec0000000077ff32a3#), array(array('disable_quote_ad...'))) called at [generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php:91]
#14 Magento\Quote\Model\QuoteManagement\Interceptor->submit(&Magento\Quote\Model\Quote\Interceptor#00000000043da0ec0000000077ff32a3#) called at [vendor/magento/module-paypal/Model/Express/Checkout.php:808]
#15 Magento\Paypal\Model\Express\Checkout->place('EC-82500173PN186...') called at [vendor/magento/module-paypal/Controller/Express/AbstractExpress/PlaceOrder.php:98]
#16 Magento\Paypal\Controller\Express\AbstractExpress\PlaceOrder->execute() called at [generated/code/Magento/Paypal/Controller/Express/PlaceOrder/Interceptor.php:24]
#17 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#18 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#19 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#20 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#21 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Magento/Paypal/Controller/Express/PlaceOrder/Interceptor.php:104]
#22 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->dispatch(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#) called at [vendor/magento/framework/App/FrontController.php:162]
#23 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#, &Magento\Paypal\Controller\Express\PlaceOrder\Interceptor#00000000043dabd50000000077ff32a3#) called at [vendor/magento/framework/App/FrontController.php:98]
#24 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#25 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#26 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#27 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000043da9da0000000077ff32a3#, &Closure#00000000043da9460000000077ff32a3#, &Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#28 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#29 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000043da9da0000000077ff32a3#, &Closure#00000000043da9460000000077ff32a3#, &Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#30 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#31 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#32 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#00000000043da8040000000077ff32a3#) called at [vendor/magento/framework/App/Http.php:116]
#33 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#34 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#35 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#00000000043da8170000000077ff32a3#) called at [index.php:39]
</pre> [] []`

any fix?

**Comment by convenient** [comment] 2020-10-09 15:17
I have been unable to replicate this issue, but with the stack trace and the [linked commit](https://github.com/magento/inventory/issues/2554#issuecomment-596567957) I've given it a go.

https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/37

I have not tested this code change at all! Just coded it up and committed. If you can repro this issue locally and can try out this change and get back to me that would be brilliant thanks

**Comment by clockworkgeek** [comment] 2021-02-16 16:00
@convenient I have this issue and sadly your fix didn't help.

I was trying to debug `GetDefaultSortedSourcesResult.php` to see what happens with normalised SKUs and found that `GetDefaultSortedSourcesResult` only gets called during checkout when this extension is enabled. Perhaps if you knew why this happens you could also prevent it?

**Comment by clockworkgeek** [comment] 2021-02-17 12:24
Eventually traced my particular problem to mismatched SKUs. The SKU in `inventory_source_item` table had a trailing space which the SKU in `catalog_product_entity` table did not have. Although it's not going to help every instance of this error I mention it in case someone lands here from Google in future.

**Comment by pixel75** [comment] 2021-02-17 21:41
> Eventually traced my particular problem to mismatched SKUs. The SKU in `inventory_source_item` table had a trailing space which the SKU in `catalog_product_entity` table did not have. Although it's not going to help every instance of this error I mention it in case someone lands here from Google in future.

This was my issue!
just run this:

`SELECT * FROM catalog_product_entity 
WHERE sku LIKE ' %';`

I have had to fix all the SKU imported from M1.9 and now is fine!

**Comment by convenient** [comment] 2021-02-18 09:24
@clockworkgeek Thank you for testing! I don't know how I would reproduce a trailing space in one table but not the other.

As there are two of you describing the same issue with the same root cause I am going to close this issue, anyone else who has this issue would be best fixing the data in their system.

**Closed by convenient** 2021-02-18 09:24 UTC
Labels: help wanted, waiting for feedback
